# Generated by Django 3.1.1 on 2021-11-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key',
        ),
    ]
